# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
    - task: CmdLine@2
      continueOnError: true
      inputs:  
        script: |
          ls -ltr
          pwd
          docker pull owasp/zap2docker-stable
          docker run --name zapserver -u zap -p 8080:8080 -i owasp/zap2docker-stable zap-x.sh -daemon -host 0.0.0.0 -port 8080 -config api.addrs.addr.name=.* -config api.addrs.addr.regex=true & 
          sleep 60s
          docker ps | grep zapserver
          IP_Address=`docker container inspect -f '{{ .NetworkSettings.IPAddress }}'`
          echo $IP_Address
          curl -v "http://$IP_Address:8080"
          ls -ltr
          mvn clean test 
          docker exec zapserver zap-cli report -o vulnerability.html -f HTML 
