# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
    - task: CmdLine@2
      continueOnError: true
      inputs:  
        script: |
          ls -ltr
          pwd
          docker pull owasp/zap2docker-stable
          docker ps
          ls -ltr
          #mvn clean test
