# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
    - task: CmdLine@2
      continueOnError: true
      inputs:  
        script: |
          ls -ltr
          pwd
          wget -q -O zap.tar.gz https://github.com/zaproxy/zaproxy/releases/download/v2.12.0/ZAP_2.12.0_Linux.tar.gz
          tar -xzf zap.tar.gz
          mv ZAP_2.12.0 zap
          ls -ltr
          cd zap
          chmod u+x zap.sh
          ./zap.sh -daemon &
          cd ..
          ls -ltr
          ps -ef
          mvn clean test